[pyprland]
plugins = ["expose", "scratchpads", "shortcuts_menu"]

[menu]
command = "rofi -dmenu -i -p ''"

[scratchpads.nvim]
animation = "fromTop"
command = "kitty --class nvim-scratch sh -c 'tmux new-session -A -s nvim-scratch \"nvim memo.txt\"'"
class = "nvim-scratch"
size = "75% 60%"
max_size = "1920px 100%"
margin = "20%"
unfocus = "hide"
lazy = true

[shortcuts_menu.entries]
"Run Script" = 'run-hypr-script'
